### ISSUE TITLE
collect OTF2 traces for debugging

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#104]
- [x] Lulesh
- [x] AMG
- [x] HPCG
- [ ] MiniDFT

~50-100 MPI ranks

This should be plenty

**Comment by jjwilke** [comment]
For MiniDFT, run using directions here:
http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/minidft

HPCG follow the README from Mantevo download.

For amg2013, run with mpirun -n64 -laplace -n 10 10 10 -P 4 4 4

**Comment by sknigh** [comment]
I have runs for everything except miniDFT. DFT is getting linker errors that I'm still sorting out.

**Comment by jjwilke** [comment]
mpi_coverage_test.cc use as input program for traces, 10 ranks
You'll need to convert from skeleton to full app then into an OTF2 trace

Remove all the I-collectives - not supported

**Comment by jjwilke** [comment]
This issue can be basically resolved when the dumpi to OTF2 conversion is working.

**Comment by jjwilke** [comment]
Consider this done with the DUMPI to OTF2 conversion tool.
