### ISSUE TITLE
Look into clang-devel packages for Mac

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#113]
Should install clang-built clang with libtooling libraries

**Comment by jpkenny** [comment]
There is a clang-devel macports package.  It does provide libTooling.  With a little path hacking it will pass configure tests.

**Comment by jpkenny** [comment]
I can generate a compile-time failure even thought configure tests pass:

```
Making all in bin
  CXX      src/sstmac_dummy_main.o
  CXX      src/top_info.o
  CXX      clang/sstmac_clang_deglobal-util.o
  CXX      clang/sstmac_clang_deglobal-globals.o
  CXX      clang/sstmac_clang_deglobal-pragmas.o
  CXX      clang/sstmac_clang_deglobal-computePragma.o
  CXX      clang/sstmac_clang_deglobal-astConsumers.o
  CXX      clang/sstmac_clang_deglobal-frontendActions.o
  CXX      clang/sstmac_clang_deglobal-replAstVisitor.o
  CXXLD    sstmac
  CXXLD    sstmac_top_info
  CXXLD    sstmac_clang_deglobal
ld: library not found for -lclang
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [sstmac_clang_deglobal] Error 1
make: *** [all-recursive] Error 1
```

**Comment by jpkenny** [comment]
"port install clang-devel" has everything we need and works as long as you provide the path with "--with-clang=PATH" (surely can be made to work in other ways, but --with-clang is the best).  The path is most likely "/opt/local/libexec/llvm-devel" unless you do something weird.  Added a configure check to increase likelihood of proper config.
