### ISSUE TITLE
autoset CC and CXX from sst-core

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#136]

**Comment by jjwilke** [comment]
sst-info or sst-config... look in sst-core bin folder

**Comment by jpkenny** [comment]
Autoset judged to be impractical (would need to propagate to SUMI/SProCKit somehow).  Added consistency checks instead, which is sufficient and a much cleaner solution.

**Comment by jjwilke** [comment]
This only works with absolute paths.  If the compiler is specified with "g++", e.g, sst-core reports as /usr/bin/g++ but this string doesn't match g++.

**Comment by jjwilke** [comment]
No autoset - but checks to make sure they are the same.

**Comment by jjwilke** [comment]
Oh wait - you didn't fix this.

**Comment by jjwilke** [comment]
NM. For non-expert users, I suspect Spack will be the main way to do this. Too annoying to check with autotools. CMake...
