### ISSUE TITLE
spack package for SST

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#144]
Complete with clang source-to-source

**Comment by jjwilke** [comment]
Don't forget to add documentation in manual - and don't forget to update markdown

**Comment by jjwilke** [comment]
Builds 7.1 and builds on clang 4.0 - but need to verify.  Make sure make check and make installcheck are running to verify.

**Comment by sknigh** [comment]
The package is ready, but the build checks don't work for 7.1

``` bash
make[3]: *** No rule to make target `test_clang_deglobal_regular.tmp-out', needed by `test_clang_deglobal_regular.chk-out'.  Stop.
make[3]: *** Waiting for unfinished jobs....
```

**Comment by sknigh** [comment]
@jjwilke The same problem persists when building with ```devel``` and ```devel-7.2```

**Comment by jjwilke** [comment]
Basically done, but not merged into mainline Spack
