### ISSUE TITLE
Find whitepapers on OmniPath and Infiniband

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#146]
See if we can figure out tiled router structures without ripping apart switches

**Comment by jjwilke** [comment]
Let's e-mail Scott and try to get in touch with someone at Mellanox and Intel

**Comment by sknigh** [comment]
Intel has some Omni-Path information on their website, but doesn't cover the internal tiling
[Adapter](https://www.intel.com/content/www/us/en/high-performance-computing-fabrics/omni-path-host-fabric-interface.html)
[Switch](https://www.intel.com/content/www/us/en/high-performance-computing-fabrics/omni-path-edge-switches-100-series.html)
A [whitepaper](https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/new-high-performance-fabric-hpc-paper.pdf) on Ompi-path mentions packet prioritization
This [slide deck](http://www.hoti.org/hoti23/slides/rimmer.pdf) from 2015 walks through the OSI layers, but conveniently leaves out the physical layer.

**Comment by jjwilke** [comment]
OmniPath paper ENABLING SCALABLE HIGH-
PERFORMANCE SYSTEMS WITH THE
INTEL OMNI-PATH ARCHITECTURE
