### ISSUE TITLE
how to speed up the simulation

### ISSUE THREAD

**Issue by YongjunZHENG** [sstsimulator/sst-macro#155]
I simulated a skeleton (only MPI communication, no computation) program of 50000 processes using standalone SST/MACRO.  The parallel simulation is slower than serial simulation, the more MPI processes or threads, the slower. I built the latest version of SST/MACRO  using CC=mpicc CXX=mpicxx or --enable-multithread, both are the same, do not speed up the simulation. Any suggestion is welcome, thank you in advance!

**Comment by jjwilke** [comment]
Can we move this conversation to the mailing list? Please send this question to sst-macro-help@sandia.gov and we can work from there.

**Comment by YongjunZHENG** [comment]
Sure, please move it to the mailing list. I posed here because I did not where to ask for help. Thanks!






At 2017-06-01 11:06:55, "Jeremy" <notifications@github.com> wrote:


Can we move this conversation to the mailing list? Please send this question to sst-macro-help@sandia.gov and we can work from there.

**Comment by jjwilke** [comment]
Sorry for the confusion. Could you send this message to the mailing list? We can't see your e-mail on the issue tracker.

**Comment by jjwilke** [comment]
Let's call this expired. Please renew questions to sst-help@sandia.gov.
