### ISSUE TITLE
Error in compiling sendrecv_sst_so

### ISSUE THREAD

**Issue by YongjunZHENG** [sstsimulator/sst-macro#156]
I tried SST/MACRO on SST/CORE. After successfully built both, I went to sst-macro/skeletons/sendrecv_sst_so and type "make", and got the following error:
sst++ -o libsendrecv.so main.o -fPIC 
Cannot create .so file: fPIC not in C/CXXFLAGS
make: *** [libsendrecv.so] Error 1

**Comment by jjwilke** [comment]
The check should have been on compilation of source files, not the linker. This is fixed in devel-7.1 branch. Changes will be pushed into main branch soon.
