### ISSUE TITLE
improve boost installation instructions in manual

### ISSUE THREAD

**Issue by jpkenny** [sstsimulator/sst-macro#175]
Instructions for installing boost in the manual are poor.  

- There are typos and syntax errors if directly cut and paste.

- runme.sh shows a gcc option with no clang equivalent.

- Doesn't seem to work as written for clang built boost

- doesn't ./b2 in runme.sh need a target?

**Comment by jpkenny** [comment]
I don't believe boost is even needed for anything involving sst-macro.  Should probably just remove mention of boost install.

**Comment by jjwilke** [comment]
Boost instructions are still there, but deferred into a "not needed" section
