### ISSUE TITLE
building sst-macro with multithread option

### ISSUE THREAD

**Issue by andreistirb** [sstsimulator/sst-macro#178]
New Issue for sst-macro
-----------------------

1 - Detailed description of problem or enhancement
File sstmac/software/process/operating_system.cc, line 188, if building with multithread option. The parent pointer, which is of type hw::node is trying to call some event_mgr method, but I didn't find anything like that in the hw::node definition.

2 - Describe how to reproduce
I could reproduce it when trying to build sst-macro with multithread option.

3 - What Operating system(s) and versions 
Ubuntu 16.04LTS

**Comment by jjwilke** [comment]
Should be fixed in the event_queues branch. Will be merged to mainline soon.
