### ISSUE TITLE
OTF2 build using OTF2 module on Kahuna leads to undefined references

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#185]
Master or devel branch. Log into Kahuna and
````
module load otf2
````

Then run configure. SST auto-detects OTF2 even without an --enable-otf2 flag.
However, after building, it complains about a bunch of undefined references.

**Comment by sknigh** [comment]
I can recreate the issue; linker errors appear when --enable-otf2 is not defined and OTF2 is in the path.

**Comment by sknigh** [comment]
Fixed by #188
