### ISSUE TITLE
otf2 test does not run correctly

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#190]
The otf2_tests test_otf2.chk-out runs an OTF2 trace, but it fails to run to completion. It deadlocks in an MPI_Wait loop.  It is not clear if the trace itself is bad or the trace replay has a bug.

**Comment by sknigh** [comment]
I haven't been able to recreate this issue on Centos 7.3 or Ubuntu 17.04. Do you have configure flags?

**Comment by jjwilke** [comment]
Done. Ranks were not getting remapped correctly.
