### ISSUE TITLE
Fix FTQ, update for matplotlib

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#212]
1) Make sure that basic MPI and compute are labeled properly in the output

2) Fix gnuplot output to reference correct file and output PDF

3) Update to also dump a matplotlib file generating similar output

**Comment by sknigh** [comment]
The outstanding issue is merging multiple ftq tag sources with the same name, which affects a small percentage of MPI tags. Outside of that, support for matplotlib-based ftq plotting is in event_queues.

**Comment by sknigh** [comment]
Final changes are in the ```event_queues``` branch

**Comment by jjwilke** [comment]
Final fixes merged in with FTQ branch
