### ISSUE TITLE
HPCG build can't find Makefile.ext

### ISSUE THREAD

**Issue by deanchester** [sstsimulator/sst-macro#251]
Following the instructions for building HPCG I got the following output: 

> deangchester@Deans-MacBook-Pro:skeletons/hpcg-3.0 $ source env.sh 
> sed: ../Makefile.ext: No such file or directory

It seems in the release this file is missing but can be obtained from the HPCG source and it disappears.

**Comment by jjwilke** [comment]
The documentation in the README file did not get updated. Assuming sst-macro is correctly installed and paths are set up, you can just type 'make'. 

The Makefile.ext is no longer used.

**Comment by jjwilke** [comment]
Documentation fixed. Will be pushed into devel.
