### ISSUE TITLE
LLVM 5.0 via clang-devel broken

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#253]

**Comment by deanchester** [comment]
As mentioned in my email to support I had worked on a fix for this which should get it working. 

It would be quite easy to make this work for either LLVM 4 or 5 with a preprocessor directive around the call to get QualType::getAsString for either version. As I have put wrapped the call in a function in clang/utils.cc. 

Also in my email I forgot to mention the other difference with LLVM 5 which is the BeginSourceFileAction function prototype has changed to [remove the file name parameter](https://github.com/llvm-mirror/clang/commit/772553c418344b6943a468b79e043180840eb255) this patch also has this done.

[llvm5-0.patch.zip](https://github.com/sstsimulator/sst-macro/files/1621643/llvm5-0.patch.zip)
