### ISSUE TITLE
openmpi and fvisibility=hidden

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#259]
when files are compiled with fvisibility=hidden, the merge step
````
ld -r tmp.X.o sstGlobals.X.o
````
converts 'D' and 'S' symbols into local 'd' and 's' symbols in the merged X.o, leading potentially to undefined references.  

We either need to find a magical flag to keep the linker from doing this or have the SST compiler essentially disallow the visibility=hidden flag.

**Comment by jpvandy** [comment]
Is this Mac or Linux or both?

**Comment by jjwilke** [comment]
Mac - but this is only for the skeleton apps compiled with sst++, not the simulator itself.

**Comment by jjwilke** [comment]
Let's call this done. visibility=hidden just gets ignored now by SST wrapper
