### ISSUE TITLE
unique_ptr breaks deglobalizer

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#286]
Need to do special work for make_unique initializers because they do not have a copy constructor

**Comment by jjwilke** [comment]
This wasn't a problem unique to unique_ptr (no pun intended). In general, any static variable initialized as a call expression...

int x = fxn()

The init function needs to be encapsulated as a lambda that gets invoked at init time.

**Comment by nmhamster** [comment]
A career in comedy beckons :-) .. you made me smile.
