### ISSUE TITLE
Weird behavior with topology unit test functions disabled

### ISSUE THREAD

**Issue by calccrypto** [sstsimulator/sst-macro#30]
When all topology unit tests are disabled except topology/test_topology in [tests/unit/tests/Makefile.am](https://github.com/sstsimulator/sst-macro/blob/master/tests/unit_tests/Makefile.am#L47) and all tests in [tests//unit_tests/topology/test_topology.h](https://github.com/sstsimulator/sst-macro/blob/master/tests/unit_tests/topology/test_topology.h) and [tests//unit_tests/topology/test_topology.c](https://github.com/sstsimulator/sst-macro/blob/master/tests/unit_tests/topology/test_topology.c) are commented out so that the first line that runs is [unit.validate();](https://github.com/sstsimulator/sst-macro/blob/master/tests/unit_tests/topology/test_topology.cc#L31), `make check` prints
`FAILED: unit_test_topology.chk-out: Line SUCCESS: fat tree coord check top_fattree.cc:58 missing from CHK file`, which makes no sense.

**Comment by jjwilke** [comment]
make check system doesn't use these now
