### ISSUE TITLE
no pthread_spinlock_t on mac 

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-macro#304]
New Issue for sst-macro
-----------------------

1 - Detailed description of problem or enhancement
Builds using --enable-spinlock fail on OSX since some functionality lives under different names: 
```
In file included from ../../../sst-macro/sstmac/common/runtime.cc:53:
In file included from ../../../sst-macro/sstmac/backends/common/parallel_runtime.h:51:
../../../sst-macro/sstmac/common/thread_lock.h:101:3: error: unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
  pthread_spinlock_t lock_;
  ^~~~~~~~~~~~~~~~~~
  pthread_rwlock_t
/usr/include/sys/_pthread/_pthread_rwlock_t.h:30:35: note: 'pthread_rwlock_t' declared here
typedef __darwin_pthread_rwlock_t pthread_rwlock_t;
                                  ^
1 error generated.
```

2 - Describe how to reproduce
Try to configure with --enable-spinlock on OSX 

3 - What Operating system(s) and versions 
OS X

4 - What version of external libraries (Boost, MPI)
Neither 

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
sst-macro -> b14225b51c09c7e6ea3ad04ddbc98f7a2deda342

This might already be a known issue, but I didn't find it by searching.

**Comment by jjwilke** [comment]
There is no spinlock supported on Mac. This should be a configure error, though, not a compile error.

**Comment by jjwilke** [comment]
Darwin gets detected in configure.ac:

````
# Find out if this is running Mac OS X.
darwin=false
case $target_os in
  darwin*)  darwin=true ;;
esac
AM_CONDITIONAL([DARWIN],[test "$darwin" = true])
````

Add a configure check that prints meaningful error if trying to add spin-lock support with darwin=true.

**Comment by jjwilke** [comment]
Isn't that still an OS-level lock that goes through kernel? Spinlock just thrashes an atomic variable. I wouldn't use os_unfair_lock_t.

If you want to try implementing this on Mac, pick 1 of 2 options:
1. OSSpinLockLock
2. Manually do this using atomics (see multithread_event_manager)

**Comment by calewis** [comment]
OSSpinLockLock is deprecated see https://developer.apple.com/documentation/os/1646466-os_unfair_lock_lock os_unfair_lock is the replacement according to that link.

**Comment by jjwilke** [comment]
"This function doesn't spin on contention, but instead waits in the kernel to be awoken by an unlock."

So your two options now are:
1. Manually with atomics
2. Throw a configure error

**Comment by calewis** [comment]
I will throw a configure error for now.
