### ISSUE TITLE
compilation fails with gcc 6.4.0 (MacPorts gcc6 6.4.0_1)

### ISSUE THREAD

**Issue by jpkenny** [sstsimulator/sst-macro#348]
jpkenny$ pwd
/Users/jpkenny/src/sst-macro-gcc6.build/tests
jpkenny$ /opt/local/bin/gcc --version
gcc (MacPorts gcc6 6.4.0_1) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

jpkenny$ make
Making all in unit_tests
Making all in util
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all-am'.
Making all in sumi
make[1]: Nothing to be done for `all'.
Making all in api/mpi
Makefile:769: warning: overriding commands for target `testexec'
Makefile:712: warning: ignoring old commands for target `testexec'
make[1]: Nothing to be done for `all'.
Making all in api/globals
Makefile:533: warning: overriding commands for target `testexec'
Makefile:483: warning: ignoring old commands for target `testexec'
make[1]: Nothing to be done for `all'.
Making all in external
make[1]: Nothing to be done for `all'.
  CXX      test_std_thread.lo
In file included from /opt/local/include/gcc6/c++/mutex:47:0,
                 from ../../sst-macro-gcc6/sstmac/replacements/mutex:11,
                 from ../../sst-macro-gcc6/tests/test_std_thread.cc:46:
/opt/local/include/gcc6/c++/thread:61:9: error: using typedef-name 'using thread = class sstmac::sw::std_thread_standin' after 'class'
   class thread
         ^~~~~~
In file included from ../../sst-macro-gcc6/tests/test_std_thread.cc:45:0:
../../sst-macro-gcc6/sstmac/replacements/thread:14:46: note: 'using thread = class sstmac::sw::std_thread_standin' has a previous declaration here
 using thread = sstmac::sw::std_thread_standin;
                                              ^
In file included from /opt/local/include/gcc6/c++/mutex:47:0,
                 from ../../sst-macro-gcc6/sstmac/replacements/mutex:11,
                 from ../../sst-macro-gcc6/tests/test_std_thread.cc:46:
/opt/local/include/gcc6/c++/thread: In function 'void std::swap(std::thread&, std::thread&)':
/opt/local/include/gcc6/c++/thread:232:9: error: 'using thread = class sstmac::sw::std_thread_standin {aka class sstmac::sw::std_thread_standin}' has no member named 'swap'
   { __x.swap(__y); }
         ^~~~
/opt/local/include/gcc6/c++/thread: At global scope:
/opt/local/include/gcc6/c++/thread:235:22: error: declaration of 'operator!=' as non-function
   operator!=(thread::id __x, thread::id __y) noexcept
                      ^~
/opt/local/include/gcc6/c++/thread:235:14: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
   operator!=(thread::id __x, thread::id __y) noexcept
              ^~~~~~
/opt/local/include/gcc6/c++/thread:235:30: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
   operator!=(thread::id __x, thread::id __y) noexcept
                              ^~~~~~
/opt/local/include/gcc6/c++/thread:239:22: error: declaration of 'operator<=' as non-function
   operator<=(thread::id __x, thread::id __y) noexcept
                      ^~
/opt/local/include/gcc6/c++/thread:239:14: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
   operator<=(thread::id __x, thread::id __y) noexcept
              ^~~~~~
/opt/local/include/gcc6/c++/thread:239:30: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
   operator<=(thread::id __x, thread::id __y) noexcept
                              ^~~~~~
/opt/local/include/gcc6/c++/thread:243:21: error: declaration of 'operator>' as non-function
   operator>(thread::id __x, thread::id __y) noexcept
                     ^~
/opt/local/include/gcc6/c++/thread:243:13: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
   operator>(thread::id __x, thread::id __y) noexcept
             ^~~~~~
/opt/local/include/gcc6/c++/thread:243:29: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
   operator>(thread::id __x, thread::id __y) noexcept
                             ^~~~~~
/opt/local/include/gcc6/c++/thread:247:22: error: declaration of 'operator>=' as non-function
   operator>=(thread::id __x, thread::id __y) noexcept
                      ^~
/opt/local/include/gcc6/c++/thread:247:14: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
   operator>=(thread::id __x, thread::id __y) noexcept
              ^~~~~~
/opt/local/include/gcc6/c++/thread:247:30: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
   operator>=(thread::id __x, thread::id __y) noexcept
                              ^~~~~~
/opt/local/include/gcc6/c++/thread:253:17: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
     struct hash<thread::id>
                 ^~~~~~
/opt/local/include/gcc6/c++/thread:253:17: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
/opt/local/include/gcc6/c++/thread:253:27: error: template argument 1 is invalid
     struct hash<thread::id>
                           ^
/opt/local/include/gcc6/c++/thread:254:34: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
     : public __hash_base<size_t, thread::id>
                                  ^~~~~~
/opt/local/include/gcc6/c++/thread:254:34: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
/opt/local/include/gcc6/c++/thread:254:44: error: template argument 2 is invalid
     : public __hash_base<size_t, thread::id>
                                            ^
/opt/local/include/gcc6/c++/thread:263:63: error: 'sstmac::sw::thread::id' has not been declared
     operator<<(basic_ostream<_CharT, _Traits>& __out, thread::id __id)
                                                               ^~
/opt/local/include/gcc6/c++/thread: In function 'std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, int)':
/opt/local/include/gcc6/c++/thread:265:19: error: 'id' is not a member of 'std::thread {aka sstmac::sw::std_thread_standin}'
       if (__id == thread::id())
                   ^~~~~~
/opt/local/include/gcc6/c++/thread:268:23: error: request for member '_M_thread' in '__id', which is of non-class type 'int'
  return __out << __id._M_thread;
                       ^~~~~~~~~
/opt/local/include/gcc6/c++/thread: At global scope:
/opt/local/include/gcc6/c++/thread:282:20: error: 'id' in 'using thread = class sstmac::sw::std_thread_standin {aka class sstmac::sw::std_thread_standin}' does not name a type
     inline thread::id
                    ^~
In file included from ../../sst-macro-gcc6/sstmac/replacements/mutex:11:0,
                 from ../../sst-macro-gcc6/tests/test_std_thread.cc:46:
/opt/local/include/gcc6/c++/mutex:365:13: error: 'id' in 'using thread = class sstmac::sw::std_thread_standin {aka class sstmac::sw::std_thread_standin}' does not name a type
     thread::id  _M_owner;
             ^~
/opt/local/include/gcc6/c++/mutex:377:15: error: 'id' in 'using thread = class sstmac::sw::std_thread_standin {aka class sstmac::sw::std_thread_standin}' does not name a type
       thread::id _M_caller;
               ^~
/opt/local/include/gcc6/c++/mutex: In member function 'bool std::recursive_timed_mutex::_Can_lock::operator()() const':
/opt/local/include/gcc6/c++/mutex:374:47: error: 'const class std::recursive_timed_mutex' has no member named '_M_owner'; did you mean '_M_count'?
       { return _M_mx->_M_count == 0 || _M_mx->_M_owner == _M_caller; }
                                               ^~~~~~~~
/opt/local/include/gcc6/c++/mutex:374:59: error: '_M_caller' was not declared in this scope
       { return _M_mx->_M_count == 0 || _M_mx->_M_owner == _M_caller; }
                                                           ^~~~~~~~~
/opt/local/include/gcc6/c++/mutex: In member function 'void std::recursive_timed_mutex::lock()':
/opt/local/include/gcc6/c++/mutex:391:19: error: 'get_id' is not a member of 'std::this_thread'
       auto __id = this_thread::get_id();
                   ^~~~~~~~~~~
/opt/local/include/gcc6/c++/mutex:392:38: error: too many initializers for 'std::recursive_timed_mutex::_Can_lock'
       _Can_lock __can_lock{this, __id};
                                      ^
/opt/local/include/gcc6/c++/mutex:397:7: error: '_M_owner' was not declared in this scope
       _M_owner = __id;
       ^~~~~~~~
/opt/local/include/gcc6/c++/mutex: In member function 'bool std::recursive_timed_mutex::try_lock()':
/opt/local/include/gcc6/c++/mutex:404:19: error: 'get_id' is not a member of 'std::this_thread'
       auto __id = this_thread::get_id();
                   ^~~~~~~~~~~
/opt/local/include/gcc6/c++/mutex:405:38: error: too many initializers for 'std::recursive_timed_mutex::_Can_lock'
       _Can_lock __can_lock{this, __id};
                                      ^
/opt/local/include/gcc6/c++/mutex:411:7: error: '_M_owner' was not declared in this scope
       _M_owner = __id;
       ^~~~~~~~
/opt/local/include/gcc6/c++/mutex: In member function 'bool std::recursive_timed_mutex::try_lock_for(const std::chrono::duration<_Rep1, _Period1>&)':
/opt/local/include/gcc6/c++/mutex:420:14: error: 'get_id' is not a member of 'std::this_thread'
  auto __id = this_thread::get_id();
              ^~~~~~~~~~~
/opt/local/include/gcc6/c++/mutex:427:2: error: '_M_owner' was not declared in this scope
  _M_owner = __id;
  ^~~~~~~~
/opt/local/include/gcc6/c++/mutex: In member function 'bool std::recursive_timed_mutex::try_lock_until(const std::chrono::time_point<_Clock, _Duration1>&)':
/opt/local/include/gcc6/c++/mutex:436:14: error: 'get_id' is not a member of 'std::this_thread'
  auto __id = this_thread::get_id();
              ^~~~~~~~~~~
/opt/local/include/gcc6/c++/mutex:443:2: error: '_M_owner' was not declared in this scope
  _M_owner = __id;
  ^~~~~~~~
/opt/local/include/gcc6/c++/mutex: In member function 'void std::recursive_timed_mutex::unlock()':
/opt/local/include/gcc6/c++/mutex:456:4: error: '_M_owner' was not declared in this scope
    _M_owner = {};
    ^~~~~~~~
make[1]: *** [test_std_thread.lo] Error 1
make: *** [all-recursive] Error 1

**Comment by jpkenny** [comment]
../sst-macro-gcc6/configure --prefix=/Users/jpkenny/install/sst-macro-gcc6 --enable-replacement-headers CXX=/opt/local/bin/g++ CC=/opt/local/bin/gcc CFLAGS=-g -O0 CXXFLAGS=-g -O0

jpkenny$ git log -1
commit 4b1571e3f1eabcc5c9c5dece748bfbf1873dc036 (HEAD -> devel, origin/devel)
Merge: f0486f76 ad655b28
Author: SST AutoTester <sst-autotester@software.sandia.gov>
Date:   Tue Jul 10 21:18:24 2018 -0600

    merge
    
    Automatically Merged using SST Pull Request AutoTester

**Comment by calewis** [comment]
@jjwilke this error appears to have to do with the fact that libstdc++ includes thread in mutex.  Then the compiler complains that thread has already been typedefed by sst-macro replacement thread.
