### ISSUE TITLE
HPCG skeleton | Getting "0" time for WAXPBY 

### ISSUE THREAD

**Issue by Vixz7** [sstsimulator/sst-macro#357]
Hi,
My apologies if this is not the right platform to ask questions related to skeleton benchmarks in SST-macro, please point me to the right platform/forum.
I am trying to run skeleton application in the sstmacro-8.0.0, while running HPCG test I am getting benchmark time summary for WAXPBY as 0 in the *yaml file:
_

> Benchmark Time Summary:
>   Optimization phase: 0
>   DDOT: 0.000256085
>   **WAXPBY: 0**
>   SpMV: 0.00010124
>   MG: 0.000419312
>   Total: 0.000776637_

I have compiled SST (CORE, Elements and macro ) using GCC-5.3.0 and OMPI-2.1.3. I tried running with different problem size and #MPI_process but getting same outcome.
Is this expected output or something is going wrong in here?

I am new to SST and appreciate any inputs or comments on this issue.

regards,
Vix

**Comment by jjwilke** [comment]
I'm really sorry. Somehow I never got a notification for this.  If this is still active, could you please send me the HPCG command-line parameters you're using? And the .ini file for SST/macro? 

In certain cases, the time is so small that the simulator just treats it as zero for the sake of optimization. This might be happening here. SpMV is tiny - and that's supposed to be the most expensive.
