### ISSUE TITLE
Make it so dirty dumpi doesn't shows as modified on git status

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-macro#360]
At some point in the configuration and building process sst-dumpi appears modified.  It can be fixed by the following: https://github.com/sstsimulator/sst-macro/commit/e9fd691cee4272f42b1e15ad0705ea9a32607ff3, 
but I am not sure if there are downsides to doing this.

**Comment by jjwilke** [comment]
This appears to be a matter of ltmain.sh not being in .gitignore.

**Comment by jjwilke** [comment]
Fixed the gitignore file instead. I'd like DUMPI to still show as modified if it has actual modifications.
