### ISSUE TITLE
Check comm ids in OTF2 writer

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#365]
```` 
OTF2_EvtWriter_MpiCollectiveEnd(evt_writer, nullptr, stop, collective, comm, root, sent, received);

OTF2_EvtWriter_MpiSend(evt_writer, nullptr, start, dest, comm, tag, type_sizes_[type]*count);
````

This comm is the local comm ID from the DUMPI trace (or SST/macro replay). Shouldn't this be the global comm ID for OTF2?

**Comment by sknigh** [comment]
You can provide an local identifier for the comm, so long as a [mapping to a global identifier](https://github.com/sstsimulator/sst-dumpi/blob/5744b8d8f8372171c81f55be43ed658bde6a58fa/dumpi/libotf2dump/otf2writer.cc#L469) is provided (that's what local def files are for).

**Comment by jjwilke** [comment]
This becomes somewhat complicated when mixing DUMPI/SST.

SST does not reuse comm IDs. DUMPI might, if MPI_Comm_free is called. If you reuse a local comm ID, then it is not valid to the use the mapping table. You must write a global ID directly to the trace.

This works out okay, actually, with the refactor. DUMPI is able to assign global comm IDs before running the main trace conversion pass. Thus it can write global comm IDs directly and skips the table.

SST cannot assign global comm IDs until the end. However, SST does not reuse local comm IDs. Thus we can write local comm IDs to the trace and add a mapping table at the end.
