### ISSUE TITLE
Adding router that uses routing tables

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#391]
Minimal routing - single port per LID

**Comment by jjwilke** [comment]
The basic router setup is there in table_router.cc

For Serrano, we will probably also want a table-based topology to initialize ports for.

**Comment by sknigh** [comment]
bin/tools/opareport_snapshot_parser.py will generate the routing tables ('-r' flag) from a topology snapshot.

**Comment by jjwilke** [comment]
Linking to #392. Possibly we should base topology/table files on JSON, just so we're locked into a standard format.
