### ISSUE TITLE
Add BSD/MIT JSON parser

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#392]
This will be helpful initially for read/write memoization models

**Comment by sknigh** [comment]
There are several choices. I am trying out https://github.com/nlohmann/json, which is a header-only JSON parser that targets C++11 features.

**Comment by sknigh** [comment]
https://github.com/sknigh/sst-macro/tree/add/json

**Comment by jjwilke** [comment]
I should have explained better. The JSON parser should be directly integrated into SST/macro - not a TPL. It looks like nlohmann provides a single include json.hpp? Can't we just copy that into our source tree as long as we keep license intact?

**Comment by sknigh** [comment]
Installation has a long cmake step, but I think it just runs tests.

I think we can use this:
https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp

**Comment by jjwilke** [comment]
Yeah, that looks like all we need. We should add a skeleton app that uses the internal JSON parser to write then read and validate.

**Comment by sknigh** [comment]
The json.hpp header includes an MIT license.

**Comment by sknigh** [comment]
@jjwilke #395 
```#include <sstmac/libraries/nlohmann/json.hpp>```

**Comment by jjwilke** [comment]
I think we can declare this done, yeah?

**Comment by jjwilke** [comment]
Done with Nlohmann stuff
