### ISSUE TITLE
cross-test all possible versions of gcc with libtooling and sst

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#406]
Test 25 combinations:

GCC 4.8.5, 4.9, 5, 6, 7 x Libtooling 4,5,6,7,8

Possibly we should have these as variants inside spack. Then you could test spack and the 25 combinations at the same time.

**Comment by sknigh** [comment]
The spec syntax is robust enough to change the dependency tree without additional variants. 

e.g. LLVM 4 with gcc 8

``` bash
spack install sst-macro+skeletonizer ^llvm@4.0.0 %gcc@8.2.0
```

**Comment by sknigh** [comment]
I have been picking away at why LLVM builds fail with some versions of GCC:

- Known LLVM 5/GCC 8 incompatibility. 5.0.2 includes a patch for that particular bug. I don't see a patched release for 4... might just be a lost cause.
https://bugzilla.redhat.com/show_bug.cgi?id=1540620
- LLVM 7 will hunt down CUDA on system paths. CUDA doesn't support > GCC 5 
https://github.com/spack/spack/issues/9591
- LLVMs not affected by the above two will generate "gcc 'this' argument discards qualifiers" errors with GCC 8.

**Comment by jjwilke** [comment]
Somehow I must have been working off a pre-release of LLVM 5.  I have source for 5.0.0, but the function signature for BeginSourceFileAction is somehow different from that in the current tarballs for 0,1,2. I will update accordingly. That should green light gcc with 5.0.x

**Comment by sknigh** [comment]
The CUDA issue is just plain dumb. I can retry LLVM 7 builds in a container to verify it will build with GCC 6 and 7. I haven't found the right flags to disable CUDA support, but it must be possible.

**Comment by sknigh** [comment]
I got sst-macro + LLVM 7 with GCC 6, 7, and 8 to build in Debian containers.

Once a fix is pushed for LLVM 5, we will have complete coverage except for LLVM 4 and LLVM 5 with GCC 8.

```
# Set up spack
git clone http://github.com/spack/spack.git
spack/bin/spackspack bootstrap

# Get the images
singularity pull docker://gcc:6
singularity pull docker://gcc:7
singularity pull docker://gcc:8

./gcc-6.simg -c "spack/bin/spack compiler find"
./gcc-7.simg -c "spack/bin/spack compiler find"
./gcc-8.simg -c "spack/bin/spack compiler find"

# Some repositories require unzip
./gcc-6.simg -c 'spack/bin/spack -k install unzip'

# Build SST
sbatch -t 2:00:00 --wrap="./gcc-6.simg -c 'export PATH=\$PATH:\$(spack/bin/spack location -i unzip)/bin; spack/bin/spack -k install sst-macro@develop+skeletonizer ^llvm@7.0.0 %gcc@6.4.0'"
sbatch -t 2:00:00 --wrap="./gcc-7.simg -c 'export PATH=\$PATH:\$(spack/bin/spack location -i unzip)/bin; spack/bin/spack -k install sst-macro@develop+skeletonizer ^llvm@7.0.0 %gcc@7.3.0'"
sbatch -t 2:00:00 --wrap="./gcc-8.simg -c 'export PATH=\$PATH:\$(spack/bin/spack location -i unzip)/bin; spack/bin/spack -k install sst-macro@develop+skeletonizer ^llvm@7.0.0 %gcc@8.2.0'"
```

**Comment by sknigh** [comment]
Successfully built develop branch with LLVM 5.0.2

**Comment by jjwilke** [comment]
We need to amend this issue to just pick a set of compiler combinations that we will support.

**Comment by jjwilke** [comment]
Good enough.
