### ISSUE TITLE
Add a clang-fromat file and use it. 

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-macro#414]
@jjwilke, this is really up to you, it's really easy to do, but we have to decide on a format and then we have to decide on if it is worth reformatting all the old files.  The downside is that it can make git blame not useful. 

Some things that we would need to do:
- [ ] Get a clang format file we are happy with (easy I hope)
- [ ] Format current files (we may want to discuss this)
- [ ] Add hooks for auto formatting on commit 

I'll look into finding a way to not destroy the history.

**Comment by jjwilke** [comment]
There are ways to do this that involves not overwriting the git blame history. Let's see if we can do a clang-format commit that doesn't change blame and then start doing this.

**Comment by calewis** [comment]
Okay, I'll have to look into how.

**Comment by calewis** [comment]
@jjwilke I don't see a way to format everything without either changing sha's or history.  Your call as to whether we do this or close it.
