### ISSUE TITLE
Skeletonization compiler workflow is fragile and complicated

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-macro#424]
I'm going to update this issue as I find problems, but immediately there appear to be 2 things.  

1. Using g++ 8.2.0 as the compiler includes builtins that need macros defined for the clang pass. 
2. It appears that the only real safe way to build with skeletonization enabled is to use the same compiler for SST as was used for the building of the llvm that will be used.

**Comment by jjwilke** [comment]
Let's close this in favor of specific issues as they arise
