### ISSUE TITLE
Using router parameter breaks with topology=simple_fattree

### ISSUE THREAD

**Issue by calccrypto** [sstsimulator/sst-macro#45]
Should `ft` be cast to a `abstract_fat_tree` instead of `fat_tree`? Also, shouldn't the check be done first, and then the variable be set?

[sstmac/hardware/router/fat_tree.cc:54](https://github.com/sstsimulator/sst-macro/blob/master/sstmac/hardware/router/fat_tree_router.cc#L54)

```
void
fat_tree_router::set_topology(topology *top)
{
  structured_router::set_topology(top);

  fat_tree* ft = safe_cast(fat_tree, top);
  if (ft->k() != k_ || ft->l() != l_){
    spkt_throw_printf(sprockit::value_error,
                      "fat tree router configuration (k=%d,l=%d) does not match"
                      " topology configuration (k=%d,l=%d)",
                      k_, l_, ft->k(), ft->l());
  }
}

```

**Comment by jjwilke** [comment]
simple_fattree updated in Nov 2016, stress tested on several traces
