### ISSUE TITLE
pragma sst new failure involving global variable

### ISSUE THREAD

**Issue by jpkenny** [sstsimulator/sst-macro#473]
"#pragma sst new" fails with the following reproducer involving a global variable.  Failure occurs on the flow-stats branch of sst-macro.

test jpkenny$ cat test.cc
#include<string.h>

int max_buffer_size = 1024 * 1024 * 4;

int main () {
  #pragma sst new
  char* buffer = new char[max_buffer_size];
  ::memset(buffer, 0, max_buffer_size);
}

test jpkenny$ SSTMAC_SKELETONIZE=1 sst++ -I. -fPIC -O3 -std=c++11 -c test.cc -o test.o
test.cc:7:34: error: expected ';' at end of declaration
 char * (*sstmac_max_buffer_size)r;
                                 ^
                                 ;
test.cc:8:19: error: use of undeclared identifier 'buffer'
  ::sstmac_memset(buffer, 0, (*sstmac_max_buffer_size));
                  ^
2 errors generated.

**Comment by jjwilke** [comment]
This been fixed.
