### ISSUE TITLE
clang-format intermediate files when temps aren't deleted

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#474]
To make intermediate source-to-source files human readable,
automatically clang format after compiling object files.

**Comment by jpvandy** [comment]
The Macro make-Dist test started failing this week and Clay, owner of other recent changes says, it’s “not his fault”.

Could you take a look at it and see if you can identify the culprit?     It does stands in the way of next week’s pending release.

Tomorrow is my 9/80 off, so I won’t really get to it until Monday.

   John
