### ISSUE TITLE
It should be easier to use the compiler wrapper as a compiler wrapper

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-macro#492]
What I would actually like is if:

```sh
sst++ --make-exe test.cpp
```

Just compiled the test.cpp with the wrapped compiler.  Then we could enable features via extra flags such as 

```sh
sst++ --make-exe --memoize test.cpp
```

, which can do the same thing as the first snippet except that it will run sstmac_clang over the memoization pragmas and link any extra libraries that memoization S2S requires.  And ideally nothing else, no deglobalization and no replacements. 

It would be nice to decouple the pragma transformations away from the replacements and deglobalization.  To me it doesn't seem necessary that they be connected.

**Comment by jjwilke** [comment]
Is this still an issue? Or did this get addressed via the addition of compiler modes?

**Comment by calewis** [comment]
I believe it did, we can reopen if a new issue arises.
