### ISSUE TITLE
Cleanup warnings for 10.1 release

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#522]
Some of the prominent warnings we are getting are:

- [ ] -Winconsistent-missing-override: void addData_impl(int src, int dst, int type, int stage
- [ ] -Wattributes: warning: ‘unused’ attribute ignored [-Wattributes]

**Comment by calewis** [comment]
@jjwilke, would you like to pick a small compiler matrix and flags to be clean for?

**Comment by jjwilke** [comment]
Default compiler warnings for:
GCC 7,8
Clang 8,9
AppleClang

After that, as much of -Wall as you can.

**Comment by calewis** [comment]
@jjwilke sst-dumpi/dumpi/bin/ascii2dumpi.c|442 col 3| warning: implicit declaration of function 'strptime' is invalid in

See https://stackoverflow.com/questions/15334558/compiler-gets-warnings-when-using-strptime-function-c for solution.  How would you like to proceed?

**Comment by calewis** [comment]
@jjwilke 
```c++
/**
 * The interface for something that can schedule messages
 */
class Component :
#if SSTMAC_INTEGRATED_SST_CORE
  public SSTIntegratedComponent,
#endif
  public EventScheduler
{
 public:
  ~Component() override {}
```
is going to make dealing with -Winconsistent-missing-override a pain.  Because whether or not a method is virtual depends on whether we are using core or not  😕

**Comment by calewis** [comment]
g++ makes this annoying  -Wattributes: warning: ‘unused’ attribute ignored [-Wattributes] even though `__attribute__((unused))` is specifically allowed, parsing order issues make it warn. But if we do `#define SSTMAC_MAYBE_UNUSED ` for `__GNUG__` then we get unused variable warnings 🤦‍♂.  For now I am just going to do 

```c++
#if defined(__GNUG__)
#pragma GCC diagnostic ignored "-Wattributes"
#endif
```
For gcc, there is no good way to push or pop this so . . .

**Comment by jjwilke** [comment]
Standalone is good enough for now. Let's delay more warnings cleanup until 10.1

**Comment by calewis** [comment]
Closing based on external conversation.
