### ISSUE TITLE
network_switch::queue_length() returns 0

### ISSUE THREAD

**Issue by calccrypto** [sstsimulator/sst-macro#56]
[packet_flow_switch::queue_length](https://github.com/sstsimulator/sst-macro/blob/d360f1fcb8dbcee0b70a33e3c6498fc6a17333f8/sstmac/hardware/packet_flow/packet_flow_switch.cc#L344) 

```
int
packet_flow_switch::queue_length(int port) const
{
  packet_flow_buffer* buf = static_cast<packet_flow_buffer*>(out_buffers_[port]);
  return buf->queue_length();
}
```

calls [packet_flow_buffer::queue_length](https://github.com/sstsimulator/sst-macro/blob/d360f1fcb8dbcee0b70a33e3c6498fc6a17333f8/sstmac/hardware/packet_flow/packet_flow_buffer.h#L24), which returns 0.

```
  virtual int
  queue_length() const {
    return 0;
  }
```

This invalidates all routers that use queue_lengths

**Comment by jjwilke** [comment]
Fixed for 6.1 release on fat_tree branch
