### ISSUE TITLE
How to add parameters to global namespace when using the integrated SST-Core?

### ISSUE THREAD

**Issue by afranques** [sstsimulator/sst-macro#615]
[Section 8.1 of the manual](https://github.com/sstsimulator/sst-macro/blob/v11.0.0_beta/docs/manual/manual.md#section-81-global-namespace) shows some parameters in the global namespace, however I believe this only applies to SST-Macro in standalone mode (not integrated with SST-Core). 

My question is, does anyone know how to add a parameter to the global namespace using the integrated SST-Core? I have managed to add my own parameters to other namespaces, like "node" and "topology", but I would like to have some parameters to be global as well. My first attempt at doing this consisted in trying to read the parameter from sstmacro-11.0.0/sstmac/main/main.cc, but I later realized this is not executed when using the integrated SST-Core.

Thanks in advance!

**Comment by jpkenny** [comment]
The params in section 8.1 just control set-up for the PDES core.

I'm not sure that there is a clean way to do the same thing in sst-core. Can you provide more detail about what you're trying to achieve?

**Comment by afranques** [comment]
Understood, thank you! What I was trying to achieve is to have a global boolean parameter in the `.ini` configuration file (for example `wireless_enabled=true/false`) so that I can then check whether that parameter is true/false from many different components (such as `node.nic`, `switch`, or `topology`) without having to add the parameter to each of these components separately (i.e. without having to add separate `node.nic.wireless_enabled`, `switch.wireless_enabled`, and `topology.wireless_enabled` parameters). If there is no clean way to have that global parameter in sst-core, then it's not a problem at all, I will add the parameter separately to each of these components.
