### ISSUE TITLE
Clarification on latency and bandwidth parameters between pisces and logp switch

### ISSUE THREAD

**Issue by afranques** [sstsimulator/sst-macro#616]
I am looking at the [small_torus.ini](https://github.com/sstsimulator/sst-macro/blob/master/configurations/small_torus.ini) configuration file (which I saw is being used in the [sendrecv skeleton test](https://github.com/sstsimulator/sst-macro/tree/v11.0.0_beta/skeletons/tests/sendrecv)), and I was wondering, since `switch.name = pisces` (which I assume then uses the latency/bandwidth values given in the `switch.link` and `switch.xbar` sections), how come there is also a `switch.logp` section, which includes the `switch.logp.out_in_latency` and `switch.logp.hop_latency` parameters? I thought that switches could either be `pisces` or `logp`, but not both. I checked the parameter definitions in [Chapter 8 of the user's manual](https://github.com/sstsimulator/sst-macro/blob/v11.0.0_beta/docs/manual/manual.md#chapter-8-detailed-parameter-listings), but there was no reference to either `switch.logp.out_in_latency` or `switch.logp.hop_latency` (although they are used in the example of [Section 3.2](https://github.com/sstsimulator/sst-macro/blob/v11.0.0_beta/docs/manual/manual.md#section-32-sst-python-files) in a similar way as in the aforementioned `small_torus.ini`).

At first I thought that since `switch.name = pisces`, the `switch.logp` section would be disregarded, but then I tried modifying the values of `switch.logp.out_in_latency` and `switch.logp.hop_latency` and I saw they affected the simulation time, which means they are being taken into consideration. I also tried modifying `switch.link.latency` and leaving `switch.logp` section as it was, just in case what was actually being disabled was the `pisces` model, but I also saw that changes in this `switch.link.latency` affected the simulation time, which means that they are all being used for calculating things. This led me to the questions: 

1. What's the difference between `switch.link.latency`, `switch.logp.out_in_latency` and `switch.logp.hop_latency`?
2. What's the difference between the [logp switch](https://github.com/sstsimulator/sst-macro/blob/v11.0.0_beta/sstmac/hardware/logp/logp_switch.cc), which I saw is the one in charge of reading the `switch.logp.out_in_latency` and `switch.logp.hop_latency` parameters, and the [pisces switch](https://github.com/sstsimulator/sst-macro/blob/v11.0.0_beta/sstmac/hardware/pisces/pisces_switch.cc), which is the one in charge of reading the `switch.link` parameters (among others)?

Thanks in advance!

**Comment by jpkenny** [comment]
The macro interconnect actually constructs both a logp and a pisces network. This is an optimization for performance for small messages. The logp network is a simple bandwidth/latency model. There's a cutoff parameter, "negligible_size", that determines which messages go over which network. If you set that to zero everything will go over the pisces network.

switch.link.latency -- latency for the pisces links
switch.logp.out_in_latency -- injection/ejection(NIC) latency for the logp network
switch.logp.hop_latency -- switch link latency for the logp network

Hope this helps,
Joe
