### ISSUE TITLE
Compilation error when trying to use Ariel element library with SST/macro

### ISSUE THREAD

**Issue by jesunsahariar** [sstsimulator/sst-macro#626]
New Issue for sst-macro
-----------------------
Hi, 

I am trying to compile SST/macro with SST-core as the PDES and the Ariel SST element. 

1 - Detailed description of problem or enhancement:

I am encountering the following error when I tried to compile SST/macro. Would greatly appreciate any help regarding how to resolve this error. Please let me know if I provide any additional information. Thanks in advance! 

```C++
$HOME/sst_core_element/sst-core/install/include/sst/core/params.h:556:12: note: declared here
     Params find_scoped_params(const std::string& scope, const char* delims = ".:") const __attribute__ ((deprecated("Params::find_scoped_params() is deprecated and will be removed in SST 12. Please use the new Params::get_scoped_params() function.  As of SST 12, only a \".\" will be allowed as a scoping delimiter.")));
            ^~~~~~~~~~~~~~~~~~
  CXX      node/simple_node.lo
../../../sstmac/hardware/node/simple_node.cc:55:10: fatal error: sst/elements/ariel/arielnotify.h: No such file or directory
 #include <sst/elements/ariel/arielnotify.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

2 - Describe how to reproduce

I attempted to compile sst/macro in the following way: 
```C++

git clone git@github.com:sstsimulator/sst-macro.git
cd sst-macro
git log
commit ab914358c050e3ad37abc6099d6673fb79b1c524 (HEAD -> master, origin/master, origin/HEAD)
Merge: 6365bee3 c4ddbffb
Author: SST AutoTester <sst-autotester@software.sandia.gov>
Date:   Tue Jul 27 07:59:09 2021 -0600

    Merge pull request #624 from sstsimulator/devel

    Automatically Merged using SST Master Branch Merger
```

```C++

mkdir build
cd build
mkdir install

../configure CXX=mpicxx CC=mpicc --prefix=$HOME/sst_core_element/sst-macro/build/install --with-sst-core=$HOME/sst_core_element/sst-core/install --with-python=/share/apps/python/anaconda3-2020.02/bin/python3-config --with-sst-elements=$HOME/sst_core_element/sst-elements/install


make GLIBCXX_USE_CXX11_ABI=1 VERBOSE=1
```

For compiling sst-core I used the following configuration command:
```C++
./configure CXX=mpicxx CC=mpicc --prefix=$HOME/sst_core_element/sst-core/install --with-python=/share/apps/python/anaconda3-2020.02/bin/python3-config
```

For compiling sst-element with Ariel, I used the following configuration command (with Intel PIN tool version 3.13):
```C++
./configure --prefix=$HOME/sst_core_element/sst-elements/install --with-sst-core=$HOME/sst_core_element/sst-core/install --with-pin=$HOME/sst_core_element/pin-3.13-98189-g60a6ef199-gcc-linux --with-python=/share/apps/python/anaconda3-2020.02/bin/python3-config
```

All the test cases in sst-element for Ariel passed successfully before I proceeded to compiling sst-macro with sst-core and sst-element with Ariel.

3 - What Operating system(s) and versions 
```
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-693.5.2.el7.x86_64
Architecture: x86-64
```

4 - What version of external libraries (Boost, MPI)
```
Currently Loaded Modulefiles:
  1) gcc/7.1.0                  2) openmpi/3.1.3              3) git/2.17.0                 4) python/anaconda3.2020.02   5) gcc/8.2.0
```
5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
```
sst-core: 7b20c810832422f229c23c05e41d41350d5b6b01  (July 17, 2021)
sst-element: c742e1400afc1141d85859923993a566650a9468 (July 17, 2021)
sst-macro: ab914358c050e3ad37abc6099d6673fb79b1c524 (July 27, 2021)
```
6 - Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by harvv** [comment]
2023 and this is still an issue.  Is there a way to disable SST Macro from trying to find/use ariel from elements?  Or is the only solution to rebuild elements without ariel?

**Comment by jpkenny** [comment]
> 2023 and this is still an issue. Is there a way to disable SST Macro from trying to find/use ariel from elements? Or is the only solution to rebuild elements without ariel?

Just don't build sst-macro with the --with-sst-elements configure flag. The elements integration never went very far and hasn't been maintained or tested. The configure option will be removed shortly to avoid further confusion.

**Comment by harvv** [comment]
> > 2023 and this is still an issue. Is there a way to disable SST Macro from trying to find/use ariel from elements? Or is the only solution to rebuild elements without ariel?
> 
> Just don't build sst-macro with the --with-sst-elements configure flag. The elements integration never went very far and hasn't been maintained or tested. The configure option will be removed shortly to avoid further confusion.

awesome, thanks.  Yeah the removal of the option will be a big help; its inclusion can potentially imply that you need elements for macro to work.
Also might be helpful, on the next revision of the documentation, to just do a Note: regarding sst-elements not being a dependency of sst macro  (maybe in Chapter 2: Building and Running SST/macro)
