### ISSUE TITLE
Does sstmacro support a node with multiple network cards

### ISSUE THREAD

**Issue by Tangqinq** [sstsimulator/sst-macro#662]
Hello!
Does sstmacro support a node with multiple network cards? (Can there be more than one nic on a node?), if supported, how to do routing.
Thank you very much in advance for your time!

**Comment by jpkenny** [comment]
Hi,
There were thoughts about supporting "multi-rail" systems at points in the past, but currently many parts of macro assume one port per node so it's not possible.
We've always just increased the injection/ejection bandwidth and at the level of abstraction that macro is working at it's not that bad of an approximation.
--Joe

**Comment by Tangqinq** [comment]
ok, thanks a lot for your answer
