### ISSUE TITLE
MPI_Reduce algorithm 

### ISSUE THREAD

**Issue by sunsirui** [sstsimulator/sst-macro#665]
Hi~
When I use MPI_Reduce to test some cases, there is a big gap between the results and the actual network test results (same configuration).
However, when I was locating the internal code of MPI_Reduce, I found that the algorithm logic in the reduce.cc file (that is, the WilkeReduceActor class of MPI_Reduce) is complicated, and it is not easy to understand it.
Do you have any design proposals or design documents about MPI_Reduce that can be shared?
Thanks a lot,

**Comment by jpkenny** [comment]
Unfortunately there isn't anyone on the project at this point that has direct knowledge of the algorithm implementations. The best information that I can offer is in the following issue:
https://github.com/sstsimulator/sst-macro/issues/625

**Comment by calewis** [comment]
With regard to the complication level of the code, based on looking at one of the OpenMPI implementations of reduce https://github.com/open-mpi/ompi/blob/6d237e85d730ed946c9f45fcd3e19b78a243203e/ompi/mca/coll/portals4/coll_portals4_reduce.c#L379

It's not obvious to me that `WilkeReduceActor` is unnecessarily complicated.

**Comment by sunsirui** [comment]
ok, thanks a lot for your answer
