### ISSUE TITLE
Collective && NB_Collective

### ISSUE THREAD

**Issue by sunsirui** [sstsimulator/sst-macro#686]
Hi:
  I found that in sstmacro, the same code implementation (same algorithm implementation and flow) is used for blocking and non-blocking communication functions. But in mvapich different send and receive implementations are used for blocking and non-blocking communication functions. Has non-blocking communication been handled separately in SST-Macro?

Thanks a lot.

**Comment by jpkenny** [comment]
As the original developers of the sst-macro mpi implementation are no longer on the project, I can't determine the rationale for the approach used for non-blocking collectives. It may have just been the quickest way to add something functionally correct.
