### ISSUE TITLE
configure fails to find MPI on Mac OS

### ISSUE THREAD

**Issue by harvv** [sstsimulator/sst-macro#701]
New Issue for sst-macro
-----------------------

1 - Detailed description of problem or enhancement
---
SST-Macro version 13.0.0 via release tarball. No modifications to source tree

When compiling SST Core, MPI is properly detected. Namely, MPI_Init is found via the following configure script actions:

     configure:17926: checking for MPI_Init
     configure:17926: mpicc -o conftest -g -O2 -Wall -Wextra -I$(top_srcdir)/src -I$(top_builddir)/src   conftest.c  >&5
     configure:17926: $? = 0
     configure:17926: result: yes

When compiling SST Macro on the **exact same machine without any configuration changes**, configure for sst-macro fails to find MPI_Init; note the difference in script actions:

     configure:22109: checking for MPI_Init
     configure:22109: g++ -o conftest -g -O2   conftest.cpp -ldl  >&5
     conftest.cpp:14:9: warning: 'VERSION' macro redefined [-Wmacro-redefined]
     #define VERSION "13.0.0"
              ^
     conftest.cpp:10:9: note: previous definition is here
     #define VERSION 13
             ^
     1 warning generated.
     Undefined symbols for architecture x86_64:
       "_MPI_Init", referenced from:
           _main in conftest-982dcc.o
     ld: symbol(s) not found for architecture x86_64
     clang: error: linker command failed with exit code 1 (use -v to see invocation)

2 - Describe how to reproduce
---
(1) Follow instructions provided on how to unpack and build SST-Macro.  Run ./configure
(2) Note that mpi.h will be found by configure, but MPI_Init will fail to be detected
 
3 - What Operating system(s) and versions 
---
Mac OS 12.6.7 , Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix

4 - What version of external libraries (Boost, MPI)
---
OpenMPI 4.1.5

**Comment by jpkenny** [comment]
Should be fine if you compile sst-macro with the openmpi compiler wrappers (CXX=mpicxx,CC=mpicc), just make sure you're getting consistent paths to everything.

**Comment by harvv** [comment]
> Should be fine if you compile sst-macro with the openmpi compiler wrappers (CXX=mpicxx,CC=mpicc), just make sure you're getting consistent paths to everything.

Yeah it seems to work if I do:
CC=mpicc CXX=mpicxx ../configure  (.....)
Might be helpful to call that out in documentation, since SST Core did not require this.
(i.e. I get why it works this way, and why it's reasonable to expect someone to do it this way if they want MPI.  It's the inconsistency with building other parts of SST (the core) that makes it confusing)

**Comment by harvv** [comment]
consider updating/clarifying docs but otherwise the issue is resolved with the above explanation
