### ISSUE TITLE
otf2 trace replay with openmp events

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#84]

**Comment by jjwilke** [comment]
Ignore openmp events by default. Have a strict mode that warns about unknown events. Make sure correct OTF2 strings are getting printed.

**Comment by sknigh** [comment]
otf2_warn_unknown_callback flag will cause the trace replay to print the name of any unknown event.

**Comment by jjwilke** [comment]
Fixed in pull request 75d1182826652e181e5f95faf6a3385df83da3e8
