### ISSUE TITLE
OTF2 added to test suite

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#93]
Small OTF2 trace should be conditionally added to test suite when otf is activated

**Comment by jjwilke** [comment]
Look at bottom of Makefile.single_tests. Follow example of traces PHONY rule and test_dumpi_manager

**Comment by jjwilke** [comment]
assume we have functions in mpi_api calls:

''''
void comm_create_with_id(...)

void group_create_with_id(....)
''''

**Comment by sknigh** [comment]
This is in branch otf2_tests, which supersedes otf2_replay
