### ISSUE TITLE
configure output doesn't contain everything

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-macro#97]
there should be a lot more information at the end of configure showing exactly what got configured

1) if sst core was activated
2) if threading was activate and whether spinlocks/affinity
3) missing stuff on MPI pdes - should say yes or no
4) whether mpi sync stats are enable
5) whether sanity checks are enabled
6) whether keyword proofreading (regex) is one
7) whether clang source-to-source is enable

**Comment by jpkenny** [comment]
@jjwilke Did the regex configure option go away?

**Comment by jpkenny** [comment]
@jjwilke For increased clarity, the subrepos should report something like  
"SST Macroscale Configuration Summary:"  
instead of  
"Configuration Summary:"

**Comment by jjwilke** [comment]
Agreed on summary title.

Regex is still there. It is changed to disabled by default.
